[package]
name = "ra"
version = "0.1.0"
edition = "2021"
authors = ["jwillman@jhics.org"]

[dependencies]
tera = "1"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4.7", features = ["derive"] }
regex = "1"
serde_json = "1.0.117"